#!/bin/sh
#===============================================================================
#
#  atheros-post-down
#
#  Copyright (C) 2014 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: Unload Atheros' wireless driver
#
#===============================================================================

set -e

[ "${IFACE}" != "wlan0" ] && exit 0

if grep -qs ath6kl_sdio /proc/modules; then
	rmmod ath6kl_sdio > /dev/null
fi
