ATH_DRV_BASEDIR := Ath6kl_LinuxRelease/Generic_Packages/compat-wireless
ATH_FIR_BASEDIR := Ath6kl_LinuxRelease/Firmware_Package/target/AR6003/hw2.1.1

ifneq ($(KERNELRELEASE),)

COMPAT_OBJS_SHIPPED := $(wildcard $(src)/$(ATH_DRV_BASEDIR)/compat/*.o_shipped)
CFG802_OBJS_SHIPPED := $(wildcard $(src)/$(ATH_DRV_BASEDIR)/net/wireless/*.o_shipped)
ATH6KL_OBJS_SHIPPED := $(wildcard $(src)/$(ATH_DRV_BASEDIR)/drivers/net/wireless/ath/ath6kl/*.o_shipped)

COMPAT_OBJS := $(subst $(src)/,,$(COMPAT_OBJS_SHIPPED:.o_shipped=.o))
CFG802_OBJS := $(subst $(src)/,,$(CFG802_OBJS_SHIPPED:.o_shipped=.o))
ATH6KL_OBJS := $(subst $(src)/,,$(ATH6KL_OBJS_SHIPPED:.o_shipped=.o))

obj-m := compat.o cfg80211.o ath6kl_sdio.o
compat-y      := $(COMPAT_OBJS)
cfg80211-y    := $(CFG802_OBJS)
ath6kl_sdio-y := $(ATH6KL_OBJS)

else #ifneq ($(KERNELRELEASE),)

## Firmware files
FIRMWARE := $(ATH_FIR_BASEDIR)/ath6kl_fw_concurrency/athtcmd_ram.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/ath6kl_fw_concurrency/athwlan.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/Digi_6203-6233-US.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/Digi_6203-6233-World.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/ath6kl_fw_concurrency/fw-4.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/ath6kl_fw_concurrency/nullTestFlow.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/ath6kl_fw_concurrency/utf.bin
ifeq ("$(DEL_PLATFORM)","cpx2")
FIRMWARE += $(ATH_FIR_BASEDIR)/calData_AR6103_Digi_X2e_B.bin
FIRMWARE += $(ATH_FIR_BASEDIR)/calData_AR6103_Digi_X2e_B_world.bin
endif

SRC := $(shell pwd)

all:
	$(MAKE) -C $(KERNEL_SRC) M=$(SRC)

modules_install:
	$(MAKE) -C $(KERNEL_SRC) M=$(SRC) modules_install
	# Install firmware
	mkdir -p $(INSTALL_MOD_PATH)/lib/firmware/ath6k/AR6003/hw2.1.1/
	install -m 0644 $(FIRMWARE) $(INSTALL_MOD_PATH)/lib/firmware/ath6k/AR6003/hw2.1.1/

endif #ifneq ($(KERNELRELEASE),)
