[board]
model = Digi International ConnectCore 95 DVK.

[GPIO]

# USER LED1
USER_LED = mca-gpio,3

# USER BUTTON1
USER_BUTTON = mca-gpio,2

[I2C]

# I2C-5 on connector J23.
DEFAULT_I2C_BUS = 4

[SPI]

# LPSPI-1 on connector J24.
DEFAULT_SPI = 0,0
