# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# Container recipes and bbappends
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "digi-containers"
BBFILE_PATTERN_digi-containers := "^${LAYERDIR}/"
BBFILE_PRIORITY_digi-containers = "7"

LAYERDEPENDS_digi-containers = "digi-dey virtualization-layer"
LAYERSERIES_COMPAT_digi-containers = "scarthgap"
