#!/bin/sh
#===============================================================================
#
#  trustfence-initramfs-init
#
#  Copyright (C) 2016 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: Init script for Trustfence initramfs
#
#===============================================================================

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Set kernel console loglevel
LOGLEVEL="$(sysctl -n kernel.printk)"
sysctl -q -w kernel.printk=4

# Launch 'rngd' to feed random data to kernel entropy pool
mkdir -p /var/run && rngd

for arg in $(cat /proc/cmdline); do
	case "${arg}" in
		init=*|rescue=1|root=*|trustfence_install=*) eval ${arg};;
	esac
done

# Translate "PARTUUID=..." to real device
root="$(findfs ${root})"

# Jump to a rescue shell if requested
if [ -n "${rescue}" ]; then
	# Expand console and respawn if exited
	while true; do
		setsid cttyhack sh -l
		sleep 1
	done
fi

# Run install script if "trustfence_install" kernel parameter exists
if [ -n "${trustfence_install}" ]; then
	trustfence-install.sh ${trustfence_install} ${root}
	sleep 1
	echo ">> Rebooting the system"
	sleep 1
	sync && reboot -f
fi

# Open LUKS encrypted device
if trustfence-tool ${root} cryptroot; then
	# Reset root variable to the decrypted mapped device
	root="/dev/mapper/cryptroot"
fi

# Mount mapped device
mkdir -p /newroot
FSTYPE="$(blkid ${root} | sed -e 's,.*TYPE="\([^"]\+\)".*,\1,g')"
mount ${FSTYPE:+-t ${FSTYPE}} ${root} /newroot

#
# Clean-up and do the switch_root to the final rootfs
#
# - explicit kill 'rngd' daemon so it doesn't leak to the final rootfs
# - restore previous kernel console loglevel
# - umount virtual filesystems
#
pkill -9 rngd
[ -n "${LOGLEVEL}" ] && sysctl -q -w kernel.printk="${LOGLEVEL}"
mount --move /dev /newroot/dev
umount /sys /proc
exec switch_root /newroot ${init:-/sbin/init}
