#!/bin/sh
#===============================================================================
#
#  Copyright (C) 2023 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: Clear bootcount value
#
#===============================================================================

case "$1" in
	start)
		echo -n "Resetting bootcount value...  "
		bootcount -r
		echo "done."
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac
