#!/bin/sh
#===============================================================================
#
#  busybox-static-nodes
#
#  Copyright (C) 2013 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#  !Description: make static device nodes from device table
#
#===============================================================================

set -e

MAKEDEVS="/sbin/makedevs"
DEVICE_TABLE_CFG="/etc/device_table"

# Create static device nodes via configuration file.
if [ -f "${DEVICE_TABLE_CFG}" ]; then
	${MAKEDEVS} -d "${DEVICE_TABLE_CFG}" / >/dev/null 2>&1
fi
